services:
  beckend:
    image: Notification_Telegram_Bot
    build:
      context: .
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:16.9

    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

    volumes:
      # 1. Persistent storage for database data
      - db_data:/var/lib/postgresql/data
      
      # 2. MANDATORY: Mount the SQL blueprint into the initialization directory
      # This ensures 'ini_db.sql' is executed on the first run.
      # The path './PostgresDataBase/ini_db.sql' should be relative to this docker-compose.yml file.
      - ./PostgresDataBase/ini_db.sql:/docker-entrypoint-initdb.d/ini_db.sql

volumes:
  db_data: